[build]
base = "docusaurus"

publish = "build"

command = "yarn run download-docs && yarn build && yarn install"

[context.production.environment]
MEILISEARCH_URL = "https://docs-search.gnoteam.com"
MEILISEARCH_INDEX_UID = "production"
MEILISEARCH_API_KEY = "22a22f25327d4bff5be707fa7ee90a731e6b6c8c5a6f13c705dafcce642caafd"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# [[headers]]
#   # Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     Content-Security-Policy = "frame-ancestors https://www.facebook.com"

#     # Multi-value headers are expressed with multi-line strings.
#   cache-control = '''
#   max-age=0,
#   no-cache,
#   no-store,
#   must-revalidate'''

#     # Basic-Auth allows you to password protect your whole site.
#     # This feature may not be available on all plans.
#     Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"
