name: Deploy docs to netlify

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy-netlify:
    name: deploy-to-netlify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: read
    steps:
    - uses: actions/checkout@v4

    - name: Set Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build docs.gno.land
      working-directory: ./docusaurus
      run: |
        yarn run download-docs
        yarn install
        yarn build
      env:
        MEILISEARCH_URL: "https://docs-search.gnoteam.com"
        MEILISEARCH_INDEX_UID: "production"
        MEILISEARCH_API_KEY: "cf93b323b625c7825c4690aa16f7ebdfd8f433a021efa40f3b986e8cf4b6415e"

    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --site gno-docs --prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
